### ISSUE TITLE
Open to Unit Tests?

### ISSUE THREAD

**Issue by Ryuno-Ki** [Doubi88/FediExpress#1]
Hey there :wave: 

I was looking into learning Godot.

As a software developer, I'm used to writing tests to help me learn a codebase.
I've seen Godot having [GUT](https://godotengine.org/asset-library/asset/1709) for this.

Would you be okay with adopting it? I can create a PR.

**Comment by Doubi88** [comment]
Hey, yes, unit tests are a really good thing. I just still didn't get into the habit of writing them before writing the working code. So feel free to do so, I have no problem with that 😊
